# Generated by Django 2.0 on 2018-09-16 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anschrift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strasse', models.IntegerField(default=None)),
                ('plz', models.IntegerField(default=None)),
                ('ort', models.CharField(max_length=25, null=True)),
                ('land', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kontaktdaten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=50, null=True)),
                ('nachname', models.CharField(max_length=50, null=True)),
                ('telefon', models.CharField(max_length=25, null=True)),
                ('handy', models.CharField(max_length=25, null=True)),
                ('fax', models.CharField(max_length=50, null=True)),
                ('mail', models.CharField(max_length=50, null=True)),
                ('homepage', models.CharField(max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kostenkalkulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, null=True)),
                ('datum', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kunden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=50, null=True)),
                ('anschrift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bueroui.Anschrift')),
                ('kontakt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bueroui.Kontaktdaten')),
            ],
        ),
        migrations.CreateModel(
            name='Positionen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.IntegerField(default=None)),
                ('kalkulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bueroui.Kostenkalkulation')),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, null=True)),
                ('einheit', models.CharField(max_length=50, null=True)),
                ('kategorie', models.CharField(max_length=50, null=True)),
                ('marke', models.CharField(max_length=50, null=True)),
                ('preis', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('beginn', models.DateTimeField(blank=True, null=True)),
                ('ende', models.DateTimeField(blank=True, null=True)),
                ('anmerkung', models.TextField(null=True)),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bueroui.Kunden')),
                ('projektleitung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projektleitung', to='bueroui.Kontaktdaten')),
                ('regieleitung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regieleitung', to='bueroui.Kontaktdaten')),
            ],
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, null=True)),
                ('datum', models.DateTimeField(blank=True, null=True)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bueroui.Projekt')),
            ],
        ),
        migrations.AddField(
            model_name='positionen',
            name='rechnung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bueroui.Rechnung'),
        ),
        migrations.AddField(
            model_name='kostenkalkulation',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bueroui.Projekt'),
        ),
    ]
